name: 港区
pref: tokyo
city: minato
start_urls:
  - "https://minatoku-sports.com/"
  - "https://minatoku-sports.com/facility/"
url_patterns:
  intro_top: "/facility/?$|/guide.*/?$"
  detail_article: "/facility/[^/]+/?$"
  skip: []
selectors:
  title:
    - "h1"
    - ".page-title"
  body:
    - "main"
    - ".content"
    - "#content"
  address_hint:
    - ".address"
    - ".location"
  equipment_blocks:
    - "table"
    - ".facility-info"
address_patterns:
  - "〒\\s*\\d{3}-\\d{4}[^\\n\\r<]*"
  - "港区[^\\n]+"
keywords:
  training:
    - "トレーニング"
    - "トレーニングパーク"
    - "ジム"
  facility:
    - "スポーツセンター"
    - "体育館"
    - "プール"
