name: 北区
pref: tokyo
city: kita
start_urls:
  - "https://www.city.kita.lg.jp/city-information/facilities/1015927/index.html"
url_patterns:
  intro_top: "/city-information/facilities/1015927/.*\\.html$"
  detail_article: "/culture-tourism-sports/sports/.+\\.html$|/city-information/facilities/.+/1018350/.+\\.html$"
  skip: []
selectors:
  title:
    - "h1"
    - "#main h1"
  body:
    - "main"
    - "#main"
    - "#contents"
  address_hint:
    - ".address"
    - ".location"
  equipment_blocks:
    - "table"
    - ".entry-content"
address_patterns:
  - "〒\\s*\\d{3}-\\d{4}[^\\n\\r<]*"
  - "東京都[^\\n]+区[^\\n]+"
keywords:
  training:
    - "トレーニング"
    - "トレーニングルーム"
  facility:
    - "スポーツセンター"
    - "総合体育館"
