name: 板橋区
pref: tokyo
city: itabashi
start_urls:
  - "https://www.city.itabashi.tokyo.jp/bunka/1005245/index.html"
url_patterns:
  intro_top: "/bunka/1005245/.*\\.html$|/shisetsu/sports/.*\\.html$"
  detail_article: "/bunka/1005245/.+\\\.html$|/shisetsu/sports/.+\\\.html$"
  skip: []
selectors:
  title:
    - "h1"
    - "#main h1"
  body:
    - "main"
    - "#main"
    - "#contents"
  address_hint:
    - ".address"
    - ".location"
  equipment_blocks:
    - "table"
    - ".entry-content"
address_patterns:
  - "〒\\s*\\d{3}-\\d{4}[^\\n\\r<]*"
  - "東京都[^\\n]+区[^\\n]+"
keywords:
  training:
    - "トレーニング"
    - "トレーニングルーム"
  facility:
    - "スポーツセンター"
    - "総合体育館"
